from .jelastic import Jelastic
from .amazon import Amazon
from .heroku import Heroku
from .rackspace import Rackspace
from .ovhcloud import OVHCloud
from .digitalocean import DigitalOcean
from .softlayer import Softlayer
from .bluemix import Bluemix
from .azure import Azure
from .cloudsigma import CloudSigma
from .nexmo import Nexmo
